image: node:12.19.0

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - yarn

tests:
  stage: test
  only:
    - branches
    - merge_requests
  script:
    - yarn test
